# Generated by Django 3.0.5 on 2021-01-02 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notify', '0002_auto_20201220_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='fromuser',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('program', 'Program'), ('report', 'Report')], default='general', max_length=24, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='notification',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_user_notification', to=settings.AUTH_USER_MODEL, verbose_name='From User'),
        ),
    ]
