# Generated by Django 3.0.5 on 2020-12-19 21:02

import autoslug.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This field is automatically determined by the system, do not interfere.', unique=True, verbose_name='Unique ID')),
                ('sequence_id', models.CharField(max_length=200, verbose_name='Sequence ID')),
                ('reward_type', models.CharField(choices=[('bounty', 'Bounty'), ('points', 'Points'), ('swag', 'Swag')], default='swag', max_length=24, verbose_name='Reward Type')),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active')], default='inactive', max_length=24, verbose_name='Program Status')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=24, verbose_name='Program Visibility')),
                ('title', models.CharField(max_length=255, verbose_name='Program Title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('website', models.URLField(verbose_name='Website')),
                ('bio', models.TextField(verbose_name='Program Biography')),
                ('policy', models.TextField(verbose_name='Program Policy')),
                ('launch_date', models.DateField(verbose_name='Launch Date')),
                ('scope_description', models.TextField(blank=True, null=True, verbose_name='Scope Description')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProgramHallOfFame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This field is automatically determined by the system, do not interfere.', unique=True, verbose_name='Unique ID')),
                ('is_top', models.BooleanField(default=False, verbose_name='Is Top')),
            ],
            options={
                'verbose_name': 'Program Hall Of Fame',
                'verbose_name_plural': 'Program Hall Of Fame',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProgramReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This field is automatically determined by the system, do not interfere.', unique=True, verbose_name='Unique ID')),
                ('sequence_id', models.CharField(max_length=200, verbose_name='Sequence ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('document_state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=24, verbose_name='Document State')),
                ('asset', models.CharField(blank=True, max_length=200, null=True, verbose_name='Asset')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=24, verbose_name='Visibility')),
                ('status', models.CharField(choices=[('in-review', 'In-Review'), ('informative', 'Informative'), ('triaged', 'Triaged'), ('need-more-info', 'Need More Information'), ('new', 'New'), ('na', 'N/A'), ('duplicated', 'Duplicated'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=24, verbose_name='Status')),
                ('category', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('duplicated', 'Duplicated'), ('closed', 'Closed')], default='new', max_length=24, verbose_name='Category')),
                ('severity', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default=None, max_length=24, null=True, verbose_name='Severity')),
                ('urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, null=True, verbose_name='URL'), size=20)),
                ('description', models.TextField(help_text='Markdown Text', verbose_name='Description')),
                ('impact', models.TextField(help_text='Markdown Text', max_length=2000, verbose_name='Impact')),
                ('recommendation', models.TextField(help_text='Markdown Text', verbose_name='Recommendation')),
            ],
            options={
                'verbose_name': 'Program Report',
                'verbose_name_plural': 'Program Reports',
                'ordering': ('-modified',),
            },
        ),
        migrations.CreateModel(
            name='ProgramTypeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('WEB', 'Web'), ('IOS', 'iOS'), ('ANDROID', 'Android'), ('NETWORK', 'Network'), ('IOT', 'Internet of Things'), ('DESKTOP', 'Desktop'), ('SOURCE_CODE', 'Source Code')], default='WEB', max_length=90, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Program Type Tag',
                'verbose_name_plural': 'Program Type Tags',
            },
        ),
        migrations.CreateModel(
            name='ProgramVulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This field is automatically determined by the system, do not interfere.', unique=True, verbose_name='Unique ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Vulnerability Name')),
            ],
            options={
                'verbose_name': 'Program Vulnerability',
                'verbose_name_plural': 'Program Vulnerabilities',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProgramScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This field is automatically determined by the system, do not interfere.', unique=True, verbose_name='Unique ID')),
                ('scope_type', models.CharField(choices=[('WEB', 'Web'), ('IOS', 'iOS'), ('ANDROID', 'Android'), ('NETWORK', 'Network'), ('IOT', 'Internet of Things'), ('DESKTOP', 'Desktop'), ('SOURCE_CODE', 'Source Code')], default='WEB', max_length=90, verbose_name='Scope Type')),
                ('scope_status', models.CharField(choices=[('in-scope', 'In-scope'), ('out-of-scope', 'Out-of-scope')], default='in-scope', max_length=24, verbose_name='Scope Status')),
                ('is_eligible', models.BooleanField(default=False, verbose_name='Eligible Bounty')),
                ('in_scope_assets', models.TextField(max_length=4000, verbose_name='In Scope Assets')),
                ('out_scope_assets', models.TextField(max_length=4000, verbose_name='Out of Scope Assets')),
                ('scope_description', models.TextField(blank=True, null=True, verbose_name='Scope Description')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_scope_program', to='programs.Program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Program Scope',
                'verbose_name_plural': 'Program Scopes',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProgramReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This field is automatically determined by the system, do not interfere.', unique=True, verbose_name='Unique ID')),
                ('swag', models.CharField(blank=True, max_length=200, null=True, verbose_name='Reward Swag')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Reward Points')),
                ('bounty', models.FloatField(default=0.0, verbose_name='Reward Bounty')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_reward_program', to='programs.Program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Program Reward',
                'verbose_name_plural': 'Program Rewards',
            },
        ),
        migrations.CreateModel(
            name='ProgramReportActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This field is automatically determined by the system, do not interfere.', unique=True, verbose_name='Unique ID')),
                ('activity_type', models.CharField(choices=[('report_is_submitted', 'Report Is Submitted'), ('change_report_status', 'Change Report Status'), ('push_report_to_customer', 'Push Report to Customer'), ('triager_applied_a_change', 'Triager Applied a Change'), ('add_comment', 'Add Comment'), ('researcher_close_report', 'Researcher Close Report'), ('customer_change_status', 'Customer Change Status'), ('combination', 'Combination')], default='add_comment', max_length=24, verbose_name='Activity Type')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('duplicated', 'Duplicated')], default=None, max_length=24, null=True, verbose_name='Status')),
                ('comment', models.TextField(max_length=2000, verbose_name='Comment')),
                ('is_closed', models.BooleanField(default=False, help_text='Researcher closed the report', verbose_name='Is Closed')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.ProgramReport', verbose_name='Program Report')),
            ],
            options={
                'verbose_name': 'Program Report Activity',
                'verbose_name_plural': 'Program Report Activities',
                'ordering': ('-created',),
            },
        ),
    ]
