# Generated by Django 3.0.5 on 2020-12-19 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0001_initial'),
        ('filemanager', '0002_filemanager_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='programreportactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='programreport',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program', verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='programreport',
            name='program_scopes',
            field=models.ManyToManyField(blank=True, to='programs.ProgramScope', verbose_name='Program Scopes'),
        ),
        migrations.AddField(
            model_name='programreport',
            name='pushed_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.ProgramReport', verbose_name='Pushed Report'),
        ),
        migrations.AddField(
            model_name='programreport',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_report_researcher', to=settings.AUTH_USER_MODEL, verbose_name='Submitted by (Researcher)'),
        ),
        migrations.AddField(
            model_name='programreport',
            name='triager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_report_triager', to=settings.AUTH_USER_MODEL, verbose_name='Approved by (Triager)'),
        ),
        migrations.AddField(
            model_name='programreport',
            name='vulnerability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.ProgramVulnerability', verbose_name='Vulnerability'),
        ),
        migrations.AddField(
            model_name='programhalloffame',
            name='hacker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_hof_hacker', to=settings.AUTH_USER_MODEL, verbose_name='Program Hacker'),
        ),
        migrations.AddField(
            model_name='programhalloffame',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_hof', to='programs.Program', verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='program',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_customer', to=settings.AUTH_USER_MODEL, verbose_name='Program Manager'),
        ),
        migrations.AddField(
            model_name='program',
            name='hackers',
            field=models.ManyToManyField(blank=True, related_name='program_hackers', to=settings.AUTH_USER_MODEL, verbose_name='Hackers'),
        ),
        migrations.AddField(
            model_name='program',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_logo', to='filemanager.FileManager'),
        ),
        migrations.AddField(
            model_name='program',
            name='tags',
            field=models.ManyToManyField(related_name='program_tags', to='programs.ProgramTypeTag', verbose_name='Program Type Tags'),
        ),
        migrations.AddField(
            model_name='program',
            name='triagers',
            field=models.ManyToManyField(blank=True, related_name='program_triagers', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Triagers'),
        ),
    ]
