# Generated by Django 3.0.5 on 2020-12-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20201220_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='end_date',
            field=models.DateField(default=None, blank=True, null=True, verbose_name='End Date'),
            preserve_default=False,
        ),
    ]
