# Generated by Django 3.0.5 on 2020-12-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_program_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='end_date',
            field=models.DateField(null=True, blank=True, verbose_name='End Date'),
        ),
    ]
