# Generated by Django 3.0.5 on 2021-01-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20201226_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programreport',
            name='status',
            field=models.CharField(choices=[('in-review', 'In-Review'), ('informative', 'Informative'), ('triaged', 'Triaged'), ('need-more-info', 'Need More Information'), ('new', 'New'), ('na', 'N/A'), ('duplicated', 'Duplicated'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('self-closed', 'Self-Closed')], default='new', max_length=24, verbose_name='Status'),
        ),
    ]
