# Generated by Django 3.0.5 on 2021-01-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20210102_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programscope',
            name='in_scope_assets',
        ),
        migrations.RemoveField(
            model_name='programscope',
            name='out_scope_assets',
        ),
        migrations.RemoveField(
            model_name='programscope',
            name='scope_description',
        ),
        migrations.AddField(
            model_name='program',
            name='out_scope_asset',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='Out of Scope Asset'),
        ),
        migrations.AddField(
            model_name='programscope',
            name='in_scope_asset',
            field=models.CharField(default="Undefined", max_length=4000, verbose_name='In Scope Asset'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='scope_description',
            field=models.TextField(default='', verbose_name='Scope Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programreport',
            name='status',
            field=models.CharField(choices=[('in-review', 'In-Review'), ('informative', 'Informative'), ('triaged', 'Triaged'), ('need-more-info', 'Need More Information'), ('new', 'New'), ('na', 'N/A'), ('duplicated', 'Duplicated'), ('resolved', 'Resolved'), ('self-closed', 'Self-Closed')], default='new', max_length=24, verbose_name='Status'),
        ),
    ]
