# Generated by Django 3.0.5 on 2021-01-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_auto_20210109_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programreportactivity',
            name='activity_type',
            field=models.CharField(choices=[('report_is_submitted', 'Report Is Submitted'), ('change_report_status', 'Change Report Status'), ('change_report_severity', 'Change Report Severity'), ('push_report_to_customer', 'Push Report to Customer'), ('triager_applied_a_change', 'Triager Applied a Change'), ('add_comment', 'Add Comment'), ('researcher_close_report', 'Researcher Close Report'), ('customer_change_status', 'Customer Change Status'), ('combination', 'Combination')], default='add_comment', max_length=24, verbose_name='Activity Type'),
        ),
        migrations.AlterField(
            model_name='programscope',
            name='in_scope_asset',
            field=models.CharField(default='Undefined', max_length=4000, verbose_name='In Scope Asset'),
        ),
    ]
