# Generated by Django 3.0.5 on 2021-01-10 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0007_auto_20210109_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='programreward',
            name='criteria',
            field=models.CharField(choices=[('na', 'N/A'), ('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='undefined', max_length=24, verbose_name='Reward Criteria'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProgramReportReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This field is automatically determined by the system, do not interfere.', unique=True, verbose_name='Unique ID')),
                ('criteria', models.CharField(choices=[('na', 'N/A'), ('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='na', max_length=24, verbose_name='Reward Criteria')),
                ('reward_type', models.CharField(choices=[('bounty', 'Bounty'), ('points', 'Points'), ('swag', 'Swag')], default='points', max_length=24, verbose_name='Reward Type')),
                ('swag', models.CharField(blank=True, max_length=200, null=True, verbose_name='Reward Swag')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Reward Points')),
                ('bounty', models.FloatField(default=0.0, verbose_name='Reward Bounty')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='programs.ProgramReport', verbose_name='Program Report')),
                ('user', models.ForeignKey(help_text='In this case user can be researcher or triager', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Researcher')),
            ],
            options={
                'verbose_name': 'Program Report Reward',
                'verbose_name_plural': 'Program Report Rewards',
                'ordering': ('-created',),
            },
        ),
    ]
