# Generated by Django 3.0.5 on 2021-01-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_auto_20210110_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programscope',
            name='is_eligible',
        ),
    ]
