# Generated by Django 3.0.5 on 2021-01-16 11:24

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_auto_20210116_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramPushedReport',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('programs.programreport',),
        ),
        migrations.AddField(
            model_name='programreport',
            name='triaged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Triaged At'),
        ),
    ]