# Generated by Django 3.0.5 on 2021-01-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_programpushedreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programpushedreport',
            options={'verbose_name': 'Program Pushed Report', 'verbose_name_plural': 'Program Pushed Reports'},
        ),
        migrations.AddField(
            model_name='programreportactivity',
            name='activity',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Activity Template'),
        ),
        migrations.AlterField(
            model_name='programreportactivity',
            name='activity_type',
            field=models.CharField(choices=[('report_is_submitted', 'Report Is Submitted'), ('change_report_status', 'Change Report Status'), ('change_report_severity', 'Change Report Severity'), ('push_report_to_customer', 'Push Report to Customer'), ('triager_applied_a_change', 'Triager Applied a Change'), ('add_comment', 'Add Comment'), ('researcher_close_report', 'Researcher Close Report'), ('customer_change_status', 'Customer Change Status'), ('combination', 'Combination'), ('triaged_reward_bounty', "Triager triaged Reward action on the researcher's report (Bounty Program)"), ('triaged_reward_swag', "Triager triaged Reward action on the researcher's report (SWAG Program)"), ('triaged_reward_points', "Triager triaged Reward action on the researcher's report (Points Program)")], default='add_comment', max_length=24, verbose_name='Activity Type'),
        ),
        migrations.AlterField(
            model_name='programreportreward',
            name='criteria',
            field=models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='na', max_length=24, verbose_name='Reward Criteria'),
        ),
        migrations.AlterField(
            model_name='programreward',
            name='criteria',
            field=models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=24, verbose_name='Reward Criteria'),
        ),
    ]
