# Generated by Django 3.0.5 on 2021-01-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_auto_20210118_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='programreportreward',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is Paid'),
        ),
        migrations.AddField(
            model_name='programreportreward',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paid At'),
        ),
        migrations.AddField(
            model_name='programreportreward',
            name='payment_note',
            field=models.TextField(blank=True, help_text='This is internal payment note (admin note), it will not appear to client', verbose_name='Payment Note'),
        ),
    ]
