# Generated by Django 3.0.5 on 2021-01-27 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0002_filemanager_user'),
        ('programs', '0012_auto_20210122_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_logo', to='filemanager.FileManager'),
        ),
    ]
