# Generated by Django 3.0.5 on 2020-12-19 21:02

from django.db import migrations, models
import main.filemanager.models.files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('title', models.CharField(default='Untitled', max_length=155, verbose_name='Title')),
                ('storage', models.CharField(choices=[('local', 'Local'), ('remote', 'Remote')], default='local', max_length=24, verbose_name='Storage')),
                ('url', models.URLField(blank=True, help_text='YouTube link e.g. https://youtu.be/0bj4i-sW44s', verbose_name='URL')),
                ('source', models.FileField(blank=True, upload_to=main.filemanager.models.files._handle_file, verbose_name='File')),
                ('size', models.BigIntegerField(default=0, verbose_name='Size')),
                ('filetype', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('audio', 'Audio'), ('document', 'Document'), ('zipped', 'Zipped'), ('url', 'URL'), ('unknown', 'Unknown')], max_length=24, null=True, verbose_name='File Type')),
                ('mimetype', models.CharField(max_length=100, null=True, verbose_name='Mime Type')),
                ('extension', models.CharField(max_length=10, null=True, verbose_name='Extension')),
            ],
            options={
                'verbose_name': 'File Manager',
                'verbose_name_plural': 'Files Manager',
                'ordering': ('-created',),
            },
        ),
    ]
