# Generated by Django 3.1.6 on 2021-03-03 12:21

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filemanager', '0002_filemanager_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This field is automatically determined by the system, do not interfere.', unique=True, verbose_name='Unique ID')),
                ('sequence_id', models.CharField(max_length=200, verbose_name='Sequence ID')),
                ('reward_type', models.CharField(choices=[('bounty', 'Bounty'), ('points', 'Points'), ('swag', 'Swag')], default='swag', max_length=24, verbose_name='Reward Type')),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active')], default='inactive', max_length=24, verbose_name='Program Status')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=24, verbose_name='Program Visibility')),
                ('title', models.CharField(max_length=255, verbose_name='Program Title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('website', models.URLField(verbose_name='Website')),
                ('bio', models.TextField(verbose_name='Program Biography')),
                ('policy', models.TextField(verbose_name='Program Policy')),
                ('launch_date', models.DateField(verbose_name='Launch Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('scope_description', models.TextField(verbose_name='Scope Description')),
                ('out_scope_asset', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Out of Scope Asset')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_customer', to=settings.AUTH_USER_MODEL, verbose_name='Program Manager')),
                ('hackers', models.ManyToManyField(blank=True, related_name='program_hackers', to=settings.AUTH_USER_MODEL, verbose_name='Hackers')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_logo', to='filemanager.filemanager')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProgramReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This field is automatically determined by the system, do not interfere.', unique=True, verbose_name='Unique ID')),
                ('sequence_id', models.CharField(max_length=200, verbose_name='Sequence ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('document_state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=24, verbose_name='Document State')),
                ('asset', models.CharField(blank=True, max_length=200, null=True, verbose_name='Asset')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=24, verbose_name='Visibility')),
                ('status', models.CharField(choices=[('in-review', 'In-Review'), ('informative', 'Informative'), ('triaged', 'Triaged'), ('need-more-info', 'Need More Information'), ('new', 'New'), ('na', 'N/A'), ('duplicated', 'Duplicated'), ('resolved', 'Resolved'), ('self-closed', 'Self-Closed')], default='new', max_length=24, verbose_name='Status')),
                ('category', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('duplicated', 'Duplicated'), ('closed', 'Closed')], default='new', max_length=24, verbose_name='Category')),
                ('severity', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default=None, max_length=24, null=True, verbose_name='Severity')),
                ('urls', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('description', models.TextField(help_text='Markdown Text', verbose_name='Description')),
                ('impact', models.TextField(help_text='Markdown Text', max_length=2000, verbose_name='Impact')),
                ('recommendation', models.TextField(help_text='Markdown Text', verbose_name='Recommendation')),
                ('triaged_at', models.DateTimeField(blank=True, null=True, verbose_name='Triaged At')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Program Report',
                'verbose_name_plural': 'Program Reports',
                'ordering': ('-modified',),
            },
        ),
        migrations.CreateModel(
            name='ProgramTypeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('WEB', 'Web'), ('IOS', 'iOS'), ('ANDROID', 'Android'), ('NETWORK', 'Network'), ('IOT', 'Internet of Things'), ('DESKTOP', 'Desktop'), ('SOURCE_CODE', 'Source Code')], default='WEB', max_length=90, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Program Type Tag',
                'verbose_name_plural': 'Program Type Tags',
            },
        ),
        migrations.CreateModel(
            name='ProgramVulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This field is automatically determined by the system, do not interfere.', unique=True, verbose_name='Unique ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Vulnerability Name')),
            ],
            options={
                'verbose_name': 'Program Vulnerability',
                'verbose_name_plural': 'Program Vulnerabilities',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProgramScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This field is automatically determined by the system, do not interfere.', unique=True, verbose_name='Unique ID')),
                ('scope_type', models.CharField(choices=[('WEB', 'Web'), ('IOS', 'iOS'), ('ANDROID', 'Android'), ('NETWORK', 'Network'), ('IOT', 'Internet of Things'), ('DESKTOP', 'Desktop'), ('SOURCE_CODE', 'Source Code')], default='WEB', max_length=90, verbose_name='Scope Type')),
                ('scope_status', models.CharField(choices=[('in-scope', 'In-scope'), ('out-of-scope', 'Out-of-scope')], default='in-scope', max_length=24, verbose_name='Scope Status')),
                ('in_scope_asset', models.CharField(default='Undefined', max_length=4000, verbose_name='In Scope Asset')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_scope_program', to='programs.program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Program Scope',
                'verbose_name_plural': 'Program Scopes',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProgramReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This field is automatically determined by the system, do not interfere.', unique=True, verbose_name='Unique ID')),
                ('criteria', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=24, verbose_name='Reward Criteria')),
                ('swag', models.CharField(blank=True, max_length=200, null=True, verbose_name='Reward Swag')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Reward Points')),
                ('bounty', models.FloatField(default=0.0, verbose_name='Reward Bounty')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_reward_program', to='programs.program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Program Reward',
                'verbose_name_plural': 'Program Rewards',
            },
        ),
        migrations.CreateModel(
            name='ProgramReportReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This field is automatically determined by the system, do not interfere.', unique=True, verbose_name='Unique ID')),
                ('criteria', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='na', max_length=24, verbose_name='Reward Criteria')),
                ('reward_type', models.CharField(choices=[('bounty', 'Bounty'), ('points', 'Points'), ('swag', 'Swag')], default='points', max_length=24, verbose_name='Reward Type')),
                ('swag', models.CharField(blank=True, max_length=200, null=True, verbose_name='Reward Swag')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Reward Points')),
                ('bounty', models.FloatField(default=0.0, verbose_name='Reward Bounty')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('payment_note', models.TextField(blank=True, help_text='This is internal payment note (admin note), it will not appear to client', verbose_name='Payment Note')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='programs.programreport', verbose_name='Program Report')),
                ('user', models.ForeignKey(help_text='In this case user can be researcher or triager', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Researcher')),
            ],
            options={
                'verbose_name': 'Program Report Reward',
                'verbose_name_plural': 'Program Report Rewards',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProgramReportActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This field is automatically determined by the system, do not interfere.', unique=True, verbose_name='Unique ID')),
                ('activity_type', models.CharField(choices=[('report_is_submitted', 'Report Is Submitted'), ('change_report_status', 'Change Report Status'), ('change_report_severity', 'Change Report Severity'), ('push_report_to_customer', 'Push Report to Customer'), ('triager_applied_a_change', 'Triager Applied a Change'), ('add_comment', 'Add Comment'), ('researcher_close_report', 'Researcher Close Report'), ('customer_change_status', 'Customer Change Status'), ('combination', 'Combination'), ('triaged_reward_bounty', "Triager triaged Reward action on the researcher's report (Bounty Program)"), ('triaged_reward_swag', "Triager triaged Reward action on the researcher's report (SWAG Program)"), ('triaged_reward_points', "Triager triaged Reward action on the researcher's report (Points Program)")], default='add_comment', max_length=24, verbose_name='Activity Type')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('duplicated', 'Duplicated')], default=None, max_length=24, null=True, verbose_name='Status')),
                ('comment', models.TextField(max_length=2000, verbose_name='Comment')),
                ('is_closed', models.BooleanField(default=False, help_text='Researcher closed the report', verbose_name='Is Closed')),
                ('activity', models.TextField(blank=True, default='', max_length=2000, verbose_name='Activity Template')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.programreport', verbose_name='Program Report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Publisher')),
            ],
            options={
                'verbose_name': 'Program Report Activity',
                'verbose_name_plural': 'Program Report Activities',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='programreport',
            name='program_scopes',
            field=models.ManyToManyField(blank=True, to='programs.ProgramScope', verbose_name='Program Scopes'),
        ),
        migrations.AddField(
            model_name='programreport',
            name='pushed_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.programreport', verbose_name='Pushed Report'),
        ),
        migrations.AddField(
            model_name='programreport',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_report_researcher', to=settings.AUTH_USER_MODEL, verbose_name='Submitted by (Researcher)'),
        ),
        migrations.AddField(
            model_name='programreport',
            name='triager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_report_triager', to=settings.AUTH_USER_MODEL, verbose_name='Approved by (Triager)'),
        ),
        migrations.AddField(
            model_name='programreport',
            name='vulnerability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.programvulnerability', verbose_name='Vulnerability'),
        ),
        migrations.CreateModel(
            name='ProgramHallOfFame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This field is automatically determined by the system, do not interfere.', unique=True, verbose_name='Unique ID')),
                ('is_top', models.BooleanField(default=False, verbose_name='Is Top')),
                ('hacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_hof_hacker', to=settings.AUTH_USER_MODEL, verbose_name='Program Hacker')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_hof', to='programs.program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Program Hall Of Fame',
                'verbose_name_plural': 'Program Hall Of Fame',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='program',
            name='tags',
            field=models.ManyToManyField(related_name='program_tags', to='programs.ProgramTypeTag', verbose_name='Program Type Tags'),
        ),
        migrations.AddField(
            model_name='program',
            name='triagers',
            field=models.ManyToManyField(blank=True, related_name='program_triagers', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Triagers'),
        ),
        migrations.CreateModel(
            name='ProgramPushedReport',
            fields=[
            ],
            options={
                'verbose_name': 'Program Pushed Report',
                'verbose_name_plural': 'Program Pushed Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('programs.programreport',),
        ),
    ]
