# Generated by Django 3.0.5 on 2020-12-19 21:02

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.users.manager.usermanager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, unique=True, verbose_name='Email address')),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Secondary Email address')),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Your phone number should consist of 9-15 digits. Example: 1114442277', regex='(\\d{9,15})$')], verbose_name='Phone Number')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='Username')),
                ('company_name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Company Name')),
                ('first_name', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Last name')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('home_address', models.TextField(blank=True, verbose_name='Home')),
                ('avatar', models.ImageField(blank=True, default='/static/assets/img/user.png', upload_to='users', verbose_name='Avatar')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('TRIAGER', 'Triager'), ('RESEARCHER', 'Researcher'), ('CUSTOMER', 'Customer')], default='RESEARCHER', max_length=50, verbose_name='User Role')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('is_email', models.BooleanField(default=False, verbose_name='Is Email Verified')),
                ('has_2fa', models.BooleanField(default=False, verbose_name='Has Two Factor Auth.')),
                ('otp_key', models.CharField(blank=True, max_length=256, null=True, verbose_name='OTP Key')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', main.users.manager.usermanager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('company_name', models.CharField(blank=True, max_length=20, verbose_name='Company Name')),
                ('password', models.CharField(max_length=40, verbose_name='Password')),
                ('email', models.EmailField(max_length=64, verbose_name='Email Address')),
                ('country', models.CharField(choices=[('EG', 'Egypt'), ('ND', 'Other')], default='EG', max_length=2, verbose_name='Country')),
                ('role', models.CharField(choices=[('researcher', 'Researcher'), ('customer', 'Customer')], default='researcher', max_length=10, verbose_name='Role')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone Number')),
                ('linkedin_profile', models.URLField(blank=True, max_length=100, verbose_name='LinkedIn Profile')),
                ('role_name', models.CharField(blank=True, max_length=40, verbose_name='Role Name')),
            ],
            options={
                'verbose_name': 'Registered User',
                'verbose_name_plural': 'Registered Users',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=240, verbose_name='Encrypted Password')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password History',
                'verbose_name_plural': 'Password Histories',
            },
        ),
    ]
