# Generated by Django 3.0.5 on 2021-01-23 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This field is automatically determined by the system, do not interfere.', unique=True, verbose_name='Unique ID')),
                ('social', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('youtube', 'Youtube'), ('github', 'Github'), ('gitlab', 'Gitlab'), ('linkedin', 'LinkedIn'), ('twitch', 'Twitch'), ('website', 'Website'), ('other', 'Other')], default='other', max_length=24, verbose_name='Social Media')),
                ('link', models.URLField(blank=True, null=True, verbose_name='link')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Social Media',
                'verbose_name_plural': 'User Social Medias',
                'ordering': ('user',),
                'unique_together': {('user', 'social')},
            },
        ),
    ]
