# Generated by Django 3.0.5 on 2021-01-27 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersocialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTraffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This field is automatically determined by the system, do not interfere.', unique=True, verbose_name='Unique ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Visit Count')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_traffic_user', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_traffic_visitor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Traffic',
                'verbose_name_plural': 'User Traffics',
                'ordering': ('-created',),
            },
        ),
    ]
