# Generated by Django 3.1.6 on 2021-02-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210210_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='BIO'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='BIO'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='email',
            field=models.EmailField(max_length=64, unique=True, verbose_name='Email Address'),
        ),
    ]
